housing/urls.py
from django.urls import path
from housing.views import *

app_name = 'housing'

urlpatterns = [
    path('export-progress/', export_progress_to_excel, name='export_progress_to_excel'),
    # ------------ COMUNIDADES ---------------
    path('communities/', CommunitiesView.as_view(), name='communities'),
    path('create_communities/', CreateCommunities.as_view(), name='create_communities'),
    path('communities/<int:pk>/edit/', EditCommunities.as_view(), name='edit_communities'),
    path('communities/<int:pk>/delete/', DeleteCommunity.as_view(), name='delete_community'),

    # ------------ PROGRESOS ---------------
    path('progress/', ProgressCommunitiesView.as_view(), name='progress'), #lista todas las comunidades
    path('progress/<int:pk>/', ComunidadDetailView.as_view(), name='comunidad_detail'), #lista los representantes de la comunidad seleccionada
    
    path('progress/<int:community_pk>/familia/<int:representante_id>/progresos/', ProgresoViviendaListView.as_view(), name='progreso_vivienda'),
    path('progress/<int:community_pk>/familia/<int:representante_id>/progresos/agregar/', AgregarProgresoView.as_view(), name='agregar_progreso'),
    path('progress/<int:community_pk>/familia/<int:representante_id>/progresos/<int:pk>/detalle/', ProgresoViviendaDetailView.as_view(), name='detalle_progreso'),
    path('progress/<int:community_pk>/familia/<int:representante_id>/progresos/<int:pk>/editar/', ProgresoViviendaUpdateView.as_view(), name='editar_progreso'),
    path('progress/<int:community_pk>/familia/<int:representante_id>/progresos/<int:pk>/eliminar/', ProgresoViviendaDeleteView.as_view(), name='eliminar_progreso'),
    path('progress/<int:community_pk>/familia/<int:representante_id>/progresos/<int:pk>/exportar-pdf/', generar_pdf_progreso, name='generar_pdf_progreso'),


    # ------------ FAMILIAS ---------------
    path('families/', FamiliesView.as_view(), name='families'),
    path('create_families/', CreateFamilies.as_view(), name='create_families'),
    path('families/<int:pk>/edit/', EditFamilies.as_view(), name='edit_families'),
    path('families/<int:pk>/delete/', DeleteFamily.as_view(), name='delete_family'),
]

mercycorpshousing/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

from housing.views import *

urlpatterns = [
    # home
    path('', IndexView.as_view(), name='inicio'),
    path('inicio/', IndexView.as_view(), name='inicio'),
    path('about/', AboutView.as_view(), name='about'),
    path('progreso/', include('housing.urls')),
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/communities/communities.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
<div class="head-title">
    <div class="left">
        <h1>Listado de comunidades</h1>
        <ul class="breadcrumb">
            <li>
                <a class="active" href="{% url 'inicio' %}">Inicio</a>
            </li>
            <li><i class='bx bx-chevron-right' ></i></li>
            <li>
                <a class="active" href="{% url 'housing:communities' %}">Comunidades</a>
            </li>
        </ul>
    </div>
</div>
<div class="default-block">
    <div class="default-content-block">
        <h2>Acciones con comunidades</h2>
        <a href="{% url 'housing:create_communities' %}" class="btn-new">
            <span class="text">&#128221; Nueva comunidad</span>
        </a>
    </div>
</div>
<div class="default-block">
    <div class="table-data">
        <div class="order">
            <div class="head">
                <h3>Comunidades</h3>              
            </div>
            <table>
                <thead>
                    <tr>
                        <th>No.</th>
                        <th>Comunidad</th>
                    </tr>
                </thead>
                <tbody>
                    {% for comunidad in comunidades %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ comunidad.nombre }}</td>
                        <td class="item-actions">
                            <a href="{% url 'housing:edit_communities' pk=comunidad.pk %}"><button class="status process">&#128221;</button></a>
                            <a href="{% url 'housing:delete_community' pk=comunidad.pk %}"><button class="status delete">&#9940;</button></a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

templates/communities/create_communities.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
<div class="head-title">
    <div class="left">
        <h1>Crear nueva comunidad</h1>
        <ul class="breadcrumb">
            <li>
                <a class="active" href="{% url 'inicio' %}">Inicio</a>
            </li>
            <li><i class='bx bx-chevron-right' ></i></li>
            <li>
                <a class="active" href="{% url 'housing:communities' %}">Comunidades</a>
            </li>
            <li><i class='bx bx-chevron-right' ></i></li>
            <li>
                <a class="active" href="{% url 'housing:create_communities' %}">Crear nueva comunidad</a>
            </li>
        </ul>
    </div>
</div>
<div class="default-block">
    <div class="table-data">
        <div class="order">
            <h1>Ingrese la información de la nueva comunidad:</h1>

            <!-- PONER EL FORM AQUI DENTRO PLOXITO  -->
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="default-block">
                    <div class="modify-block">
                        <button type="submit" class="btn-save">&#128190; Guardar</button>
                        <a href="{% url 'housing:communities' %}" class="btn-edit">
                            <span class="text">&#9940; Cancelar</span>
                        </a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}
<!-- Block javascript -->
{% block javascript %}
{% endblock %}

templates/communities/delete_community.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
<div class="head-title">
    <div class="left">
        <h1>Eliminar comunidad</h1>
        <ul class="breadcrumb">
            <li>
                <a class="active" href="{% url 'inicio' %}">Inicio</a>
            </li>
            <li><i class='bx bx-chevron-right' ></i></li>
            <li>
                <a class="active" href="{% url 'housing:communities' %}">Comunidades</a>
            </li>
            <li><i class='bx bx-chevron-right' ></i></li>
            <li>
                <a class="" href="#">Eliminar comunidad</a>
            </li>
        </ul>
    </div>
</div>
<div class="default-block">
    <div class="table-data">
        <div class="order">
            <h1>¿Está seguro de que desea eliminar la comunidad {{ comunidad.nombre }}?</h1>
            <br>
            <strong>ADVERTENCIA:</strong>
            <p>Esta acción no se puede deshacer.</p>
            <p>Tome en cuenta que <strong>{{ comunidad.nombre }}</strong> puede tener familias y progresos adjuntas en registros. Si elimina la comunidad, eliminará también los registros de familia y progresos que posee.</p>
            <br>
            <strong>¿Está segudo que desea continuar?</strong>
            <br>
            <!-- PONER EL FORM AQUI DENTRO PLOXITO  -->
            <form method="POST">
                {% csrf_token %}
                <div class="default-block">
                    <div class="modify-block">
                        <button type="submit" class="btn-delete">&#128128; Eliminar</button>
                        <a href="{% url 'housing:communities' %}" class="btn-edit">
                            <span class="text">&#9940; Cancelar</span>
                        </a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}
<!-- Block javascript -->
{% block javascript %}
{% endblock %}

templates/communities/edit_communities.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
<div class="head-title">
    <div class="left">
        <h1>Editar comunidad</h1>
        <ul class="breadcrumb">
            <li>
                <a class="active" href="{% url 'inicio' %}">Inicio</a>
            </li>
            <li><i class='bx bx-chevron-right' ></i></li>
            <li>
                <a class="active" href="{% url 'housing:communities' %}">Comunidades</a>
            </li>
            <li><i class='bx bx-chevron-right' ></i></li>
            <li>
                <a class="" href="">Editar comunidad</a>
            </li>
        </ul>
    </div>
</div>
<div class="default-block">
    <div class="table-data">
        <div class="order">
            <h1>Modifique la información de la comunidad {{comunidad.nombre}}:</h1>

            <!-- PONER EL FORM AQUI DENTRO PLOXITO  -->
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="default-block">
                    <div class="modify-block">
                        <button type="submit" class="btn-save">&#128190; Guardar</button>
                        <a href="{% url 'housing:communities' %}" class="btn-edit">
                            <span class="text">&#9940; Cancelar</span>
                        </a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}
<!-- Block javascript -->
{% block javascript %}
{% endblock %}