housing/urls.py
from django.urls import path
from housing.views import *

app_name = 'housing'

urlpatterns = [
    path('export-progress/', export_progress_to_excel, name='export_progress_to_excel'),
    # ------------ COMUNIDADES ---------------
    path('communities/', CommunitiesView.as_view(), name='communities'),
    path('create_communities/', CreateCommunities.as_view(), name='create_communities'),
    path('communities/<int:pk>/edit/', EditCommunities.as_view(), name='edit_communities'),
    path('communities/<int:pk>/delete/', DeleteCommunity.as_view(), name='delete_community'),

    # ------------ PROGRESOS ---------------
    path('progress/', ProgressCommunitiesView.as_view(), name='progress'), #lista todas las comunidades
    path('progress/<int:pk>/', ComunidadDetailView.as_view(), name='comunidad_detail'), #lista los representantes de la comunidad seleccionada
    
    path('progress/<int:community_pk>/familia/<int:representante_id>/progresos/', ProgresoViviendaListView.as_view(), name='progreso_vivienda'),
    path('progress/<int:community_pk>/familia/<int:representante_id>/progresos/agregar/', AgregarProgresoView.as_view(), name='agregar_progreso'),
    path('progress/<int:community_pk>/familia/<int:representante_id>/progresos/<int:pk>/detalle/', ProgresoViviendaDetailView.as_view(), name='detalle_progreso'),
    path('progress/<int:community_pk>/familia/<int:representante_id>/progresos/<int:pk>/editar/', ProgresoViviendaUpdateView.as_view(), name='editar_progreso'),
    path('progress/<int:community_pk>/familia/<int:representante_id>/progresos/<int:pk>/eliminar/', ProgresoViviendaDeleteView.as_view(), name='eliminar_progreso'),
    path('progress/<int:community_pk>/familia/<int:representante_id>/progresos/<int:pk>/exportar-pdf/', generar_pdf_progreso, name='generar_pdf_progreso'),


    # ------------ FAMILIAS ---------------
    path('families/', FamiliesView.as_view(), name='families'),
    path('create_families/', CreateFamilies.as_view(), name='create_families'),
    path('families/<int:pk>/edit/', EditFamilies.as_view(), name='edit_families'),
    path('families/<int:pk>/delete/', DeleteFamily.as_view(), name='delete_family'),
]

mercycorpshousing/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

from housing.views import *

urlpatterns = [
    # home
    path('', IndexView.as_view(), name='inicio'),
    path('inicio/', IndexView.as_view(), name='inicio'),
    path('about/', AboutView.as_view(), name='about'),
    path('progreso/', include('housing.urls')),
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/families/create_families.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
<div class="head-title">
    <div class="left">
        <h1>Crear nueva familia</h1>
        <ul class="breadcrumb">
            <li>
                <a class="active" href="{% url 'inicio' %}">Inicio</a>
            </li>
            <li><i class='bx bx-chevron-right' ></i></li>
            <li>
                <a class="active" href="{% url 'housing:families' %}">Familias</a>
            </li>
            <li><i class='bx bx-chevron-right' ></i></li>
            <li>
                <a class="active" href="{% url 'housing:create_families' %}">Crear nueva familia</a>
            </li>
        </ul>
    </div>
</div>
<div class="default-block">
    <div class="table-data">
        <div class="order">
            <h1>Ingrese la información del representante de la familia:</h1>

            <!-- PONER EL FORM AQUI DENTRO PLOXITO  -->
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="default-block">
                    <div class="modify-block">
                        <button type="submit" class="btn-save">&#128190; Guardar</button>
                        <a href="{% url 'housing:families' %}" class="btn-edit">
                            <span class="text">&#9940; Cancelar</span>
                        </a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}
<!-- Block javascript -->
{% block javascript %}
{% endblock %}

templates/families/delete_family.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
<div class="head-title">
    <div class="left">
        <h1>Eliminar familia</h1>
        <ul class="breadcrumb">
            <li>
                <a class="active" href="{% url 'inicio' %}">Inicio</a>
            </li>
            <li><i class='bx bx-chevron-right' ></i></li>
            <li>
                <a class="active" href="{% url 'housing:families' %}">Familias</a>
            </li>
            <li><i class='bx bx-chevron-right' ></i></li>
            <li>
                <a class="" href="#">Eliminar familia</a>
            </li>
        </ul>
    </div>
</div>
<div class="default-block">
    <div class="table-data">
        <div class="order">
            <h1>¿Está seguro de que desea eliminar la familia {{ familia.nombre }}?</h1>
            <br>
            <strong>ADVERTENCIA:</strong>
            <p>Esta acción no se puede deshacer.</p>
            <p>Tome en cuenta que <strong>{{ familia.nombre }}</strong> puede tener progresos guardados. Si elimina la familia, eliminará también los registros de progresos que posee.</p>
            <br>
            <strong>¿Está segudo que desea continuar?</strong>
            <br>
            <!-- PONER EL FORM AQUI DENTRO PLOXITO  -->
            <form method="POST">
                {% csrf_token %}
                <div class="default-block">
                    <div class="modify-block">
                        <button type="submit" class="btn-delete">&#128128; Eliminar</button>
                        <a href="{% url 'housing:communities' %}" class="btn-edit">
                            <span class="text">&#9940; Cancelar</span>
                        </a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}
<!-- Block javascript -->
{% block javascript %}
{% endblock %}

templates/families/edit_families.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
<div class="head-title">
    <div class="left">
        <h1>Editar familia</h1>
        <ul class="breadcrumb">
            <li>
                <a class="active" href="{% url 'inicio' %}">Inicio</a>
            </li>
            <li><i class='bx bx-chevron-right' ></i></li>
            <li>
                <a class="active" href="{% url 'housing:families' %}">Familias</a>
            </li>
            <li><i class='bx bx-chevron-right' ></i></li>
            <li>
                <a class="" href="">Editar familia</a>
            </li>
        </ul>
    </div>
</div>
<div class="default-block">
    <div class="table-data">
        <div class="order">
            <h1>Modifique la información de la familia {{familia.nombre}}:</h1>

            <!-- PONER EL FORM AQUI DENTRO PLOXITO  -->
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="default-block">
                    <strong>IMPORTANTE:</strong>
                    <p>Si cambia de comunidad a <strong>{{ familia.nombre }}</strong> se actualizará automáticamente en el listado de progresos, por lo que el representante y sus progresos aparecerán con la nueva comunidad seleccionada.</p>
                    <br>
                    <strong>Por favor, verifique la información antes de continuar.</strong>
                    <br><br>
                    <div class="modify-block">
                        <button type="submit" class="btn-save">&#128190; Guardar</button>
                        <a href="{% url 'housing:families' %}" class="btn-edit">
                            <span class="text">&#9940; Cancelar</span>
                        </a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}
<!-- Block javascript -->
{% block javascript %}
{% endblock %}

templates/families/families.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
<div class="head-title">
    <div class="left">
        <h1>Listado de familias</h1>
        <ul class="breadcrumb">
            <li>
                <a class="active" href="{% url 'inicio' %}">Inicio</a>
            </li>
            <li><i class='bx bx-chevron-right' ></i></li>
            <li>
                <a class="active" href="{% url 'housing:families' %}">Familias</a>
            </li>
        </ul>
    </div>
</div>
<div class="default-block">
    <div class="default-content-block">
        <h2>Acciones con familias</h2>
        <a href="{% url 'housing:create_families' %}" class="btn-new">
            <span class="text">&#128221; Nueva familia</span>
        </a>
    </div>
</div>
<div class="default-block">
    <div class="table-data">
        <div class="order">
            <div class="head">
                <h3>Familias</h3>              
            </div>
            <table>
                <thead>
                    <tr>
                        <th>No.</th>
                        <th>Familia</th>
                        <th>Comunidad</th>
                    </tr>
                </thead>
                <tbody>
                    {% for familia in familias %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ familia.nombre }}</td>
                        <td>{{ familia.comunidad }}</td>
                        <td class="item-actions">
                            <a href="{% url 'housing:edit_families' pk=familia.pk %}"><button class="status process">&#128221;</button></a>
                            <a href="{% url 'housing:delete_family' pk=familia.pk %}"><button class="status delete">&#9940;</button></a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}