housing/urls.py
from django.urls import path
from housing.views import *

app_name = 'housing'

urlpatterns = [
    path('export-progress/', export_progress_to_excel, name='export_progress_to_excel'),
    # ------------ COMUNIDADES ---------------
    path('communities/', CommunitiesView.as_view(), name='communities'),
    path('create_communities/', CreateCommunities.as_view(), name='create_communities'),
    path('communities/<int:pk>/edit/', EditCommunities.as_view(), name='edit_communities'),
    path('communities/<int:pk>/delete/', DeleteCommunity.as_view(), name='delete_community'),

    # ------------ PROGRESOS ---------------
    path('progress/', ProgressCommunitiesView.as_view(), name='progress'), #lista todas las comunidades
    path('progress/<int:pk>/', ComunidadDetailView.as_view(), name='comunidad_detail'), #lista los representantes de la comunidad seleccionada
    
    path('progress/<int:community_pk>/familia/<int:representante_id>/progresos/', ProgresoViviendaListView.as_view(), name='progreso_vivienda'),
    path('progress/<int:community_pk>/familia/<int:representante_id>/progresos/agregar/', AgregarProgresoView.as_view(), name='agregar_progreso'),
    path('progress/<int:community_pk>/familia/<int:representante_id>/progresos/<int:pk>/detalle/', ProgresoViviendaDetailView.as_view(), name='detalle_progreso'),
    path('progress/<int:community_pk>/familia/<int:representante_id>/progresos/<int:pk>/editar/', ProgresoViviendaUpdateView.as_view(), name='editar_progreso'),
    path('progress/<int:community_pk>/familia/<int:representante_id>/progresos/<int:pk>/eliminar/', ProgresoViviendaDeleteView.as_view(), name='eliminar_progreso'),
    path('progress/<int:community_pk>/familia/<int:representante_id>/progresos/<int:pk>/exportar-pdf/', generar_pdf_progreso, name='generar_pdf_progreso'),


    # ------------ FAMILIAS ---------------
    path('families/', FamiliesView.as_view(), name='families'),
    path('create_families/', CreateFamilies.as_view(), name='create_families'),
    path('families/<int:pk>/edit/', EditFamilies.as_view(), name='edit_families'),
    path('families/<int:pk>/delete/', DeleteFamily.as_view(), name='delete_family'),
]

mercycorpshousing/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

from housing.views import *

urlpatterns = [
    # home
    path('', IndexView.as_view(), name='inicio'),
    path('inicio/', IndexView.as_view(), name='inicio'),
    path('about/', AboutView.as_view(), name='about'),
    path('progreso/', include('housing.urls')),
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/about.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
<div class="head-title">
    <div class="left">
        <h1>MERCY CORPS</h1>
        <ul class="breadcrumb">
            <li>
                <a class="active" href="{% url 'inicio' %}">Inicio</a>
            </li>
            <li><i class='bx bx-chevron-right' ></i></li>
            <li>
                <a class="active" href="{% url 'about' %}">Acerca de...</a>
            </li>
        </ul>
    </div>
</div>
<div class="default-block">
    <div class="location-block">
        <div class="location-column">
            <div id="location-text">
                <h1>Ubícanos</h1>
            </div>
            <br>
            <div class="location-info">
                <strong>Mercy Corps:</strong>
                <p>Mercy Corps está trabajando en Guatemala desde el año 2001, implementando diferentes proyectos de desarrollo rural, prevención de violencia, resolución y transformación de conflictos, respondiendo a desastres y crisis en las áreas más vulnerables del país.
                    A través de nuestros programas de desarrollo, lideramos iniciativas que han tenido impactos positivos en las poblaciones que más lo necesitan, generando desarrollo y brindando esperanza a las familias más vulnerables.</p>
                <br/>
                <strong>Dirección:</strong>
                <p>3 Calle 2-24, zona 2, Cobán, Alta Verapaz, Guatemala.</p>
                <br/>
                <strong>Teléfono:</strong>
                <p>+502 7793-0810</p>
            </div>
        </div>
        <div class="maps-column">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d961.3208105387677!2d-90.37457975556974!3d15.469189449575008!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x858a417a5e6ad325%3A0xcfa3833829f41862!2sMercy%20Corps%20Guatemala!5e0!3m2!1ses!2sgt!4v1723438318989!5m2!1ses!2sgt" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
        </div>
    </div>
</div>
{% endblock %}
<!-- Block javascript -->
{% block javascript %}
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <!-- Boxicons -->
	<link href='https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css' rel='stylesheet'>

    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">

    
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

templates/footer.html
<!-- Main Footer -->
<footer class="main-footer text-center">
    
    <strong>Copyright &copy; 2024 <a href="#">Mercy Corps</a>.</strong>
    <p>Todos los derechos reservados.</p>
</footer>

templates/header.html
{% load static %}
<!-- CONTENT -->
    <!-- NAVBAR -->
    <nav>
        <i class='bx bx-menu' ></i>
        <form action="#">
        </form>
        <input type="checkbox" id="switch-mode" hidden>
        <label for="switch-mode" class="switch-mode"></label>
        
    </nav>
    <!-- NAVBAR -->
    
<!-- CONTENT -->

{% block javascript %}
{% endblock %}

templates/index.html
{% extends 'layout.html' %}
{% load static %}
{% block head %}
{% endblock %}

{% block content %}
<div class="head-title">
    <div class="left">
        <h1>Inicio</h1>
        <ul class="breadcrumb">
            <li>
                <a href="{% url 'inicio' %}">Inicio</a>
            </li>
        </ul>
    </div>
</div>

<div class="default-block">
    <div class="main-content">
        <h1>Plan de manejo de vivienda y patio</h1>
        <br>
        <p>Nuestra nueva aplicación de seguimiento de viviendas es una herramienta poderosa diseñada específicamente para optimizar y gestionar el progreso de lotificación y desarrollo de viviendas en diversas comunidades.</p>
        <br>
        <p>Esta plataforma intuitiva permite monitorizar en tiempo real el avance de las familias. Con ella, podemos identificar de manera efectiva qué comunidades están aprovechando mejor los recursos y tomar decisiones informadas para maximizar el impacto del proyecto.</p>   
        </div>
</div>

<br><br>

<div class="buttonpdf">
    <a href="{% url 'housing:export_progress_to_excel' %}" class="btn-download">
        <i class='bx bxs-cloud-download' ></i>
        <span class="text">Descargar Excel</span>
    </a>
</div>

<ul class="box-info">
    <li>
        <i class='bx bxs-calendar-check' ></i>
        <span class="text">
            <h3>5</h3>
            <p>Años de proyección</p>
        </span>
    </li>
    <li>
        <i class='bx bxs-group' ></i>
        <span class="text">
            <h3>+180</h3>
            <p>Familias</p>
        </span>
    </li>
    <li>
        <i class='bx bxs-dollar-circle' ></i>
        <span class="text">
            <h3>7</h3>
            <p>Comunidades</p>
        </span>
    </li>
</ul>



{% endblock %}

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <link rel="icon" href="{% static 'img/casa.png' %}" type="image/png"/>
    <title>{{ title }}</title>
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <!-- Boxicons -->
	<link href='https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css' rel='stylesheet'>

    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">

    <!-- Block javascript -->
    {% block javascript %}
    <script>
        (function() {
            const currentTheme = localStorage.getItem('theme');
            if (currentTheme) {
                document.body.classList.add(currentTheme);
            }
        })();
    </script>
    {% endblock %}
    
    <!-- Block head -->
    {% block head %}

    {% endblock %}
</head>
{% block body %}
<!-- Sidebar -->
{% include 'sidebar.html' %}
<!-- MAIN -->
<section class="content">
<!-- Header -->
{% include 'header.html' %}
<main>
    {% block content %}

    {% endblock %}
</main>
<!-- MAIN -->
<!-- Footer -->
{% include 'footer.html' %}
</section>

{% endblock %}

<!-- Functions -->
<script src="{% static 'js/functions.js' %}" crossorigin="anonymous"></script>
</html>

templates/sidebar.html
{% load static %}
<!-- SIDEBAR -->
<section id="sidebar">
    <a href="#" class="brand">
        <i class='bx bxs-smile'></i>
        <span class="text">Admin</span>
    </a>
    <ul class="side-menu top">
        <li class="active">
            <a href="{% url 'inicio' %}">
                <span class="text">&nbsp;&nbsp; &#127968; &nbsp; Inicio</span>
            </a>
        </li>
        <li>
            <a href="{% url 'housing:communities' %}">
                <span class="text">&nbsp;&nbsp; &#129517; &nbsp; Comunidades</span>
            </a>
        </li>
        <li>
            <a href="{% url 'housing:families' %}">
                <span class="text">&nbsp;&nbsp; &#128101; &nbsp; Familias</span>
            </a>
        </li>
        <li>
            <a href="{% url 'housing:progress' %}">
                <span class="text">&nbsp;&nbsp; &#128202; &nbsp; Progresos</span>
            </a>
        </li>
        <br>
        <li>
            <a href="{% url 'about' %}">
                <span class="text">&nbsp;&nbsp; &#128205; &nbsp; Acerca de...</span>
            </a>
        </li>
    </ul>
    <ul class="side-menu">
        <li>
            <form method="post" action="{% url 'logout' %}" class="logout">
                {% csrf_token %}
                <button type="submit" class="logout-btn">&#9940; Cerrar sesión</button>
            </form>
        </li>
    </ul>
</section>
<!-- SIDEBAR -->
{% block javascript %}
{% endblock %}