housing/urls.py
from django.urls import path
from housing.views import *

app_name = 'housing'

urlpatterns = [
    path('export-progress/', export_progress_to_excel, name='export_progress_to_excel'),
    # ------------ COMUNIDADES ---------------
    path('communities/', CommunitiesView.as_view(), name='communities'),
    path('create_communities/', CreateCommunities.as_view(), name='create_communities'),
    path('communities/<int:pk>/edit/', EditCommunities.as_view(), name='edit_communities'),
    path('communities/<int:pk>/delete/', DeleteCommunity.as_view(), name='delete_community'),

    # ------------ PROGRESOS ---------------
    path('progress/', ProgressCommunitiesView.as_view(), name='progress'), #lista todas las comunidades
    path('progress/<int:pk>/', ComunidadDetailView.as_view(), name='comunidad_detail'), #lista los representantes de la comunidad seleccionada
    
    path('progress/<int:community_pk>/familia/<int:representante_id>/progresos/', ProgresoViviendaListView.as_view(), name='progreso_vivienda'),
    path('progress/<int:community_pk>/familia/<int:representante_id>/progresos/agregar/', AgregarProgresoView.as_view(), name='agregar_progreso'),
    path('progress/<int:community_pk>/familia/<int:representante_id>/progresos/<int:pk>/detalle/', ProgresoViviendaDetailView.as_view(), name='detalle_progreso'),
    path('progress/<int:community_pk>/familia/<int:representante_id>/progresos/<int:pk>/editar/', ProgresoViviendaUpdateView.as_view(), name='editar_progreso'),
    path('progress/<int:community_pk>/familia/<int:representante_id>/progresos/<int:pk>/eliminar/', ProgresoViviendaDeleteView.as_view(), name='eliminar_progreso'),
    path('progress/<int:community_pk>/familia/<int:representante_id>/progresos/<int:pk>/exportar-pdf/', generar_pdf_progreso, name='generar_pdf_progreso'),


    # ------------ FAMILIAS ---------------
    path('families/', FamiliesView.as_view(), name='families'),
    path('create_families/', CreateFamilies.as_view(), name='create_families'),
    path('families/<int:pk>/edit/', EditFamilies.as_view(), name='edit_families'),
    path('families/<int:pk>/delete/', DeleteFamily.as_view(), name='delete_family'),
]

mercycorpshousing/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

from housing.views import *

urlpatterns = [
    # home
    path('', IndexView.as_view(), name='inicio'),
    path('inicio/', IndexView.as_view(), name='inicio'),
    path('about/', AboutView.as_view(), name='about'),
    path('progreso/', include('housing.urls')),
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/progress/communities.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
<div class="head-title">
    <div class="left">
        <h1>Progresos por comunidad</h1>
        <ul class="breadcrumb">
            <li>
                <a class="active" href="{% url 'inicio' %}">Inicio</a>
            </li>
            <li><i class='bx bx-chevron-right' ></i></li>
            <li>
                <a class="active" href="{% url 'housing:progress' %}">Comunidades</a>
            </li>
        </ul>
    </div>
</div>
<div class="default-block">
    <div class="table-data">
        <div class="order">
            <div class="head">
                <h3>Selecciona la comunidad para agregar un progreso:</h3>              
            </div>
            <table>
                <thead>
                    <tr>
                        <th>No.</th>
                        <th>Comunidad</th>
                    </tr>
                </thead>
                <tbody>
                    {% for comunidad in comunidades %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td><a href="{% url 'housing:comunidad_detail' comunidad.pk %}">{{ comunidad.nombre }}</a></td>
                        <td class="item-actions">
                            <a href="{% url 'housing:comunidad_detail' comunidad.pk %}"><button class="status completed">Ver progreso &#128200;</button></a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

templates/progress/create_progress.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
<div class="head-title">
    <div class="left">
        <h1>Crear nuevo progreso</h1>
        <ul class="breadcrumb">
            <li>
                <a class="active" href="{% url 'inicio' %}">Inicio</a>
            </li>
            <li><i class='bx bx-chevron-right' ></i></li>
            <li>
                <a class="active" href="{% url 'housing:progress' %}">Comunidades</a>
            </li>
            <li><i class='bx bx-chevron-right' ></i></li>
            <li>
                <a class="active" href="{% url 'housing:comunidad_detail' pk=community_pk %}">Representantes de familia</a>
            </li>
            <li><i class='bx bx-chevron-right' ></i></li>
            <li>
                <a class="active" href="{% url 'housing:progreso_vivienda' community_pk=community_pk representante_id=representante_id %}">Progresos</a>
            </li>
            <li><i class='bx bx-chevron-right' ></i></li>
            <li>
                <a class="active" href="{% url 'housing:agregar_progreso' community_pk=community_pk representante_id=representante_id %}">Crear nuevo progreso</a>
            </li>
        </ul>
    </div>
</div>
<div class="default-block">
    <div class="table-data">
        <div class="order">
            <h1>Agregar progreso para {{ familia.nombre }} en la comunidad {{ comunidad.nombre }}</h1>

            <!-- PONER EL FORM AQUI DENTRO PLOXITO  -->
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="default-block">
                    <div class="modify-block">
                        <button type="submit" class="btn-save">&#128190; Guardar</button>
                        <a href="{% url 'housing:progreso_vivienda' community_pk=comunidad.pk representante_id=familia.id %}" class="btn-edit">
                            <span class="text">&#9940; Cancelar</span>
                        </a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}
<!-- Block javascript -->
{% block javascript %}
{% endblock %}

templates/progress/delete_progress.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
<div class="head-title">
    <div class="left">
        <h1>Eliminar progreso</h1>
        <ul class="breadcrumb">
            <li>
                <a class="active" href="{% url 'inicio' %}">Inicio</a>
            </li>
            <li><i class='bx bx-chevron-right' ></i></li>
            <li>
                <a class="active" href="{% url 'housing:progress' %}">Comunidades</a>
            </li>
            <li><i class='bx bx-chevron-right' ></i></li>
            <li>
                <a class="active" href="{% url 'housing:comunidad_detail' pk=community_pk %}">Representantes de familia</a>
            </li>
            <li><i class='bx bx-chevron-right' ></i></li>
            <li>
                <a class="active" href="{% url 'housing:progreso_vivienda' community_pk=community_pk representante_id=representante_id %}">Progresos</a>
            </li>
            <li><i class='bx bx-chevron-right' ></i></li>
            <li>
                <a class="" href="#">Eliminar progreso</a>
            </li>
        </ul>
    </div>
</div>
<div class="default-block">
    <div class="table-data">
        <div class="order">
            <h1>¿Está seguro de que desea eliminar el progreso de la familia {{ familia.nombre }}?</h1>
            <br>
            <strong>ADVERTENCIA:</strong>
            <p>Esta acción no se puede deshacer</p>
            <br>
            <!-- PONER EL FORM AQUI DENTRO PLOXITO  -->
            <form method="POST">
                {% csrf_token %}
                <div class="default-block">
                    <div class="modify-block">
                        <button type="submit" class="btn-delete">&#128128; Eliminar</button>
                        <a href="{% url 'housing:progreso_vivienda' community_pk=community.pk representante_id=familia.id %}" class="btn-edit">
                            <span class="text">&#9940; Cancelar</span>
                        </a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}
<!-- Block javascript -->
{% block javascript %}
{% endblock %}

templates/progress/edit_progress.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
<div class="head-title">
    <div class="left">
        <h1>Editar progreso</h1>
        <ul class="breadcrumb">
            <li>
                <a class="active" href="{% url 'inicio' %}">Inicio</a>
            </li>
            <li><i class='bx bx-chevron-right' ></i></li>
            <li>
                <a class="active" href="{% url 'housing:progress' %}">Comunidades</a>
            </li>
            <li><i class='bx bx-chevron-right' ></i></li>
            <li>
                <a class="active" href="{% url 'housing:comunidad_detail' pk=community.pk %}">Representantes de familia</a>
            </li>
            <li><i class='bx bx-chevron-right' ></i></li>
            <li>
                <a class="active" href="{% url 'housing:progreso_vivienda' community_pk=community_pk representante_id=representante_id %}">Progresos</a>
            </li>
            <li><i class='bx bx-chevron-right' ></i></li>
            <li>
                <a class="" href="#">Editar progreso</a>
            </li>
        </ul>
    </div>
</div>
<div class="default-block">
    <div class="table-data">
        <div class="order">
            <h1>Editar progreso para {{ familia.nombre }} de la comunidad {{ comunidad.nombre }}</h1>

            <!-- PONER EL FORM AQUI DENTRO PLOXITO  -->
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="default-block">
                    <div class="modify-block">
                        <button type="submit" class="btn-save">&#128190; Guardar</button>
                        <a href="{% url 'housing:progreso_vivienda' community_pk=community_pk representante_id=familia.id %}" class="btn-edit">
                            <span class="text">&#9940; Cancelar</span>
                        </a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}
<!-- Block javascript -->
{% block javascript %}
{% endblock %}

templates/progress/families.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
<div class="head-title">
    <div class="left">
        <h1>Progresos por familia</h1>
        <ul class="breadcrumb">
            <li>
                <a class="active" href="{% url 'inicio' %}">Inicio</a>
            </li>
            <li><i class='bx bx-chevron-right' ></i></li>
            <li>
                <a class="active" href="{% url 'housing:progress' %}">Comunidades</a>
            </li>
            <li><i class='bx bx-chevron-right' ></i></li>
            <li>
                <a class="active" href="{% url 'housing:families' %}">Representantes de familia</a>
            </li>
        </ul>
    </div>
</div>
<div class="default-block">
    <div class="table-data">
        <div class="order">
            <div class="head">
                <h3>Representantes de la comunidad: {{ comunidad.nombre }}</h3>              
            </div>
            <table>
                <thead>
                    <tr>
                        <th>No.</th>
                        <th>Representante</th>
                    </tr>
                </thead>
                <tbody>
                    {% for familia in familias %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td><a href="{% url 'housing:progreso_vivienda' community_pk=comunidad.pk representante_id=familia.id %}">{{ familia.nombre }}</a></td>
                        <td class="item-actions">
                            <a href="{% url 'housing:progreso_vivienda' community_pk=comunidad.pk representante_id=familia.id %}"><button class="status completed">Ver progreso &#128200;</button></a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

templates/progress/family_progress.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
<div class="head-title">
    <div class="left">
        <h1>Progresos de familia</h1>
        <ul class="breadcrumb">
            <li>
                <a class="active" href="{% url 'inicio' %}">Inicio</a>
            </li>
            <li><i class='bx bx-chevron-right' ></i></li>
            <li>
                <a class="active" href="{% url 'housing:progress' %}">Comunidades</a>
            </li>
            <li><i class='bx bx-chevron-right' ></i></li>
            <li>
                <a class="active" href="{% url 'housing:comunidad_detail' pk=community_pk %}">Representantes de familia</a>
            </li>
            <li><i class='bx bx-chevron-right' ></i></li>
            <li>
                <a class="active" href="{% url 'housing:progreso_vivienda' community_pk=community_pk representante_id=representante_id %}">Progresos</a>
            </li>
        </ul>
    </div>
</div>
<div class="default-block">
    <div class="default-content-block">
        <h2>Acciones con progresos</h2>
        <a href="{% url 'housing:agregar_progreso' community_pk=community_pk representante_id=representante_id %}" class="btn-new">
            <span class="text">&#128221; Nuevo progreso</span>
        </a>
    </div>
</div>
<div class="default-block">
    <div class="table-data">
        <div class="order">
            <div class="head">
                <h3>Progresos de la familia: {{ familia.nombre }}</h3>              
            </div>
            <table>
                <thead>
                    <tr>
                        <th>Registro.</th>
                        <th>Fecha</th>
                        <th>Progreso</th>
                    </tr>
                </thead>
                <tbody>
                    {% for progreso in progresos %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td><a href="{% url 'housing:detalle_progreso' community_pk=community_pk representante_id=representante_id pk=progreso.pk %}">{{ progreso.fecha_registro }}</a></td>
                        <td>{{ progreso.promedio_progreso }}%</td>
                        <td class="item-actions">
                            <a href="{% url 'housing:detalle_progreso' community_pk=community_pk representante_id=representante_id pk=progreso.pk %}"><button class="status completed">Ver &#128200;</button></a>
                            <a href="{% url 'housing:editar_progreso' community_pk=community_pk representante_id=representante_id pk=progreso.pk %}"><button class="status process">&#128221;</button></a>
                            <a href="{% url 'housing:eliminar_progreso' community_pk=community_pk representante_id=representante_id pk=progreso.pk %}"><button class="status delete">&#9940;</button></a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}